### ISSUE TITLE
Memorize Decorator

### ISSUE THREAD

**Issue by ahilmer** [michaelfairley/method_decorators#21]
Hi,

why does the memorize decorator create a new random instance variable `@memo_ivar = "@_memoize_cache#{rand(10**10)}" `?

You could just create a empty cache like this:

`

    def initialize
	  @cache = {}
    end

    def call(orig, this, *args, &blk)
      return @cache[args] if @cache.has_key?(args)
      @cache[args] = orig.call(*args, &blk)
    end

`

Are there any reasons?

Best regard,
Andi

**Comment by michaelfairley** [comment]
2 reasons:
- A single instance of `Memoize ` is shared across all instances of a class that uses it. If the cache were stored on the `Memoize` instance, the caches values would be shared across instances of the class that includes it.
- Because of ^^^, the cache need to get stored on the instance of the decorated object, but we need to make sure that multiple memoized methods on the same class don't use the same cache. (Admittedly, `rand(10**10)` is not the best way to get this uniqueness.)

This is easily one of the most awkward parts of this library, and why I wouldn't recommend using it for anything important.

**Comment by ahilmer** [comment]
Only one single instance of `Memoize`? I think there is always a new instance of `Memoize ` created when a method gets decorated. So every single instance of `Memoize` can have its own cache variable. And there is no more  need to store the cache on the instance which gets decorated?

**Comment by michaelfairley** [comment]
There's one instance per decorated method, which is "shared" by all instance of the class where that method is defined. If we stored state directly on that instance, the state would bleed across instances of the decorated class.
